# Generated by Django 2.1.2 on 2018-11-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('author', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('image', models.TextField(blank=True, null=True)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('link', models.TextField()),
                ('category', models.TextField()),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
